# Generated by Django 5.1.2 on 2024-11-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
