# Generated by Django 5.1.2 on 2024-11-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_portfolio_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
