# Generated by Django 5.1.2 on 2024-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_projeto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='categoria',
        ),
    ]
