# Generated by Django 5.1.2 on 2024-11-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mensagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
