# Generated by Django 5.1.2 on 2024-11-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_message_recipient_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_criacao',
        ),
    ]
