# Generated by Django 5.1.2 on 2024-11-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_projeto_filtro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
